notifications:
  email: false

language: node_js
sudo: false
node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: $MOECOOP_DOMAIN
  on:
    branch: master
