notifications:
  email: false

language: node_js
sudo: false
node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test
  - yarn run build

after_success:
  - cd build
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && ./deploy.sh'
